# ===================================================================
# Spring Boot configuration.
# ===================================================================

# ===================================================================
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
logging:
  config: "@logging.config@"
  
server:
  port: 8080
  
management:
  security:
    enabled: false
  
security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin

eureka:
  instance:
#    instanceId: testId1
    metadata-map:
      instanceId: abc123456
      zone: zone1
      test.meta: abc123
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka/
#    preferSameZoneEureka: true
#eureka:
#  instance:
#    hostname: registry
#    prefer-ip-address: true
#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
#  client:
#    service-url:
#      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ztgoto/spring-cloud-sample"
          force-pull: true
          search-paths: "config-repo/{application}/{profile}"
#          username: ""
#          password: ""
#          repos:
#            simple: https://github.com/simple/config-repo
#            special:
#              pattern: special*/dev*,*special*/dev*
#              uri: https://github.com/special/config-repo
#            local:
#              pattern: local*
#              uri: file:/home/configsvc/config-repo
#  rabbitmq:
#    host: "192.168.4.137"
#    port: 5672
#    username: guest
#    password: guest
#  cloud:
#    stream:
#      instance-count: 3
#      instance-index: 0
#      bindings:
#        inputMessage:
#          destination: test_input_message
#          group: test
#          binder: kafka1
#          content-type: ""
#          consumer:
#            partitioned: true
#          producer:
#            partitionKeyExpression: payload.msg
#        outputMessage:
#          destination: test_input_message
#        inputEvent:
#          destination: test_input_event
#        outputEvent:
#          destination: test_input_event
#      binders:
#        kafka1:
#          type: kafka
#          environment:
#            spring:  
#              cloud:  
#                stream:  
#                  kafka:  
#                    binder:  
#                      brokers: name87:9094  
#                      zkNodes: name85:2181,name86:2181,name87:2181/kafka0101  

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/zhangxd1989/spring-boot-cloud
#          search-paths: config-repo
#  rabbitmq:
#    host: rabbitmq

